/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects_.$slug'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAuthedRouteImport } from './routes/admin/_authed'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin/_authed.index'
import { Route as AdminAuthedSettingsRouteImport } from './routes/admin/_authed.settings'
import { Route as AdminAuthedMessagesRouteImport } from './routes/admin/_authed.messages'
import { Route as AdminAuthedCategoriesRouteImport } from './routes/admin/_authed.categories'
import { Route as AdminAuthedAnalyticsRouteImport } from './routes/admin/_authed.analytics'
import { Route as AdminAuthedProjectsIndexRouteImport } from './routes/admin/_authed.projects.index'
import { Route as AdminAuthedProjectsNewRouteImport } from './routes/admin/_authed.projects.new'
import { Route as AdminAuthedProjectsIdRouteImport } from './routes/admin/_authed.projects.$id'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects_/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedSettingsRoute = AdminAuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedMessagesRoute = AdminAuthedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedCategoriesRoute = AdminAuthedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedAnalyticsRoute = AdminAuthedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedProjectsIndexRoute =
  AdminAuthedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AdminAuthedRoute,
  } as any)
const AdminAuthedProjectsNewRoute = AdminAuthedProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedProjectsIdRoute = AdminAuthedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AdminAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/analytics': typeof AdminAuthedAnalyticsRoute
  '/admin/categories': typeof AdminAuthedCategoriesRoute
  '/admin/messages': typeof AdminAuthedMessagesRoute
  '/admin/settings': typeof AdminAuthedSettingsRoute
  '/admin/': typeof AdminAuthedIndexRoute
  '/admin/projects/$id': typeof AdminAuthedProjectsIdRoute
  '/admin/projects/new': typeof AdminAuthedProjectsNewRoute
  '/admin/projects/': typeof AdminAuthedProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/admin/analytics': typeof AdminAuthedAnalyticsRoute
  '/admin/categories': typeof AdminAuthedCategoriesRoute
  '/admin/messages': typeof AdminAuthedMessagesRoute
  '/admin/settings': typeof AdminAuthedSettingsRoute
  '/admin': typeof AdminAuthedIndexRoute
  '/admin/projects/$id': typeof AdminAuthedProjectsIdRoute
  '/admin/projects/new': typeof AdminAuthedProjectsNewRoute
  '/admin/projects': typeof AdminAuthedProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/services': typeof ServicesRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/projects_/$slug': typeof ProjectsSlugRoute
  '/admin/_authed/analytics': typeof AdminAuthedAnalyticsRoute
  '/admin/_authed/categories': typeof AdminAuthedCategoriesRoute
  '/admin/_authed/messages': typeof AdminAuthedMessagesRoute
  '/admin/_authed/settings': typeof AdminAuthedSettingsRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
  '/admin/_authed/projects/$id': typeof AdminAuthedProjectsIdRoute
  '/admin/_authed/projects/new': typeof AdminAuthedProjectsNewRoute
  '/admin/_authed/projects/': typeof AdminAuthedProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/services'
    | '/admin'
    | '/admin/login'
    | '/admin/reset-password'
    | '/projects/$slug'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin/'
    | '/admin/projects/$id'
    | '/admin/projects/new'
    | '/admin/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/services'
    | '/admin/login'
    | '/admin/reset-password'
    | '/projects/$slug'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/messages'
    | '/admin/settings'
    | '/admin'
    | '/admin/projects/$id'
    | '/admin/projects/new'
    | '/admin/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/projects'
    | '/services'
    | '/admin/_authed'
    | '/admin/login'
    | '/admin/reset-password'
    | '/projects_/$slug'
    | '/admin/_authed/analytics'
    | '/admin/_authed/categories'
    | '/admin/_authed/messages'
    | '/admin/_authed/settings'
    | '/admin/_authed/'
    | '/admin/_authed/projects/$id'
    | '/admin/_authed/projects/new'
    | '/admin/_authed/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  ServicesRoute: typeof ServicesRoute
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$slug': {
      id: '/projects_/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/settings': {
      id: '/admin/_authed/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAuthedSettingsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/messages': {
      id: '/admin/_authed/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminAuthedMessagesRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/categories': {
      id: '/admin/_authed/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAuthedCategoriesRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/analytics': {
      id: '/admin/_authed/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAuthedAnalyticsRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/projects/': {
      id: '/admin/_authed/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminAuthedProjectsIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/projects/new': {
      id: '/admin/_authed/projects/new'
      path: '/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminAuthedProjectsNewRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/projects/$id': {
      id: '/admin/_authed/projects/$id'
      path: '/projects/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AdminAuthedProjectsIdRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
  }
}

interface AdminAuthedRouteChildren {
  AdminAuthedAnalyticsRoute: typeof AdminAuthedAnalyticsRoute
  AdminAuthedCategoriesRoute: typeof AdminAuthedCategoriesRoute
  AdminAuthedMessagesRoute: typeof AdminAuthedMessagesRoute
  AdminAuthedSettingsRoute: typeof AdminAuthedSettingsRoute
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
  AdminAuthedProjectsIdRoute: typeof AdminAuthedProjectsIdRoute
  AdminAuthedProjectsNewRoute: typeof AdminAuthedProjectsNewRoute
  AdminAuthedProjectsIndexRoute: typeof AdminAuthedProjectsIndexRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedAnalyticsRoute: AdminAuthedAnalyticsRoute,
  AdminAuthedCategoriesRoute: AdminAuthedCategoriesRoute,
  AdminAuthedMessagesRoute: AdminAuthedMessagesRoute,
  AdminAuthedSettingsRoute: AdminAuthedSettingsRoute,
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
  AdminAuthedProjectsIdRoute: AdminAuthedProjectsIdRoute,
  AdminAuthedProjectsNewRoute: AdminAuthedProjectsNewRoute,
  AdminAuthedProjectsIndexRoute: AdminAuthedProjectsIndexRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  ServicesRoute: ServicesRoute,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
